name: getnet_payments
description: getnet_payments é um plugin que fornece integração com as máquinas de pagamento da empresa Getnet.
version: 0.0.2
homepage: https://github.com/CarvalhoWesley/getnet_payments

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.5

flutter:
  plugin:
    platforms:
      android:
        package: br.com.joelabs.getnet_payments
        pluginClass: GetnetPaymentsPlugin